version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    container_name: baobab-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ADMIN_PASSWORD=baobab123
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    container_name: baobab-frontend
    ports:
      - "3000:80"
    restart: unless-stopped
