# frontend/Dockerfile.frontend
FROM node:20-alpine AS builder

WORKDIR /app
COPY frontend/ /app

RUN npm install
RUN npm run build

# Serveur léger pour les fichiers statiques
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
